config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"
  
  resources :posts do
    collection do
      post :confirm
    end
  end

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts

    has_many :favorites, dependent: :destroy

    has_many :favorite_users, through: :favorites, source: :user

    has_secure_password

    before_validation {email.downcase!}

    mount_uploader :image, ImageUploader

    validates :pseudo, presence: true, length: {maximum: 30}

    validates :email, presence: true, uniqueness: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  }
    
    validates :password, presence: true, length: {minimum:6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required

    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
      @favorites = current_user.favorites.all
      puts @favorites
  end
  
  def create
      favorite = current_user.favorites.create(post_id: params[:post_id])
      redirect_to post_path(params[:post_id]), notice: "#{favorite.post.user.pseudo}, ce post a été ajouté a vos favoris"
  end

  def destroy
    favorite = current_user.favorites.find_by(post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id]), notice: "post enlevé des favoris de M. #{favorite.post.user.pseudo}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def confirm
    @post =Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        PostMailer.post_mailer(current_user).deliver
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content, :image, :user_id, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]

    def new
    end

    def create
      user =  User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
          redirect_to posts_path
      else
        flash.now[:danger] = "Email ou mot de passe incorrect !"
        render :new
      end
    end

    def destroy
      session.delete(:user_id)
      flash[:notice] = 'Vous etes deconnecté !'
      redirect_to new_session_path
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [ :new, :create]


  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:pseudo, :email, :password, :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_posts_path
        elsif action_name == 'edit'
            post_path
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous">

<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
     rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>

<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color:#fff;">
    <div class="container justify-content-center layout">
        <div class="d-flex flex-row justify-content-between align-items-center col-10">
            <a class="navbar-brand" href="#">
                <%= image_tag("ig-logo.png", :alt => "logo") %>
            </a>
            <div class="form-data">
                <form class="" action="#">
                  <input type="text" name="" value="" placeholder="search">
                </form>
            </div>
            <div class="d-flex flex-row">
                <ul class="list-inline m-0">
                    <li class="list-inline-item">
                      <%= link_to posts_path do %>
                        <span class="material-icons" style="color:#000;">home</span>
                      <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to favorites_path do %>
                          <span class="material-icons" style="color:#000;">favorite</span>
                        <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to new_post_path do %>
                          <span class="material-icons" style="color:#000;">add_circle</span>
                        <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to user_path(current_user.id) do%>
                          <%= image_tag current_user.image.url, class:"img-fluid rounded-circle", width:"25px", height:"auto", style:"margin-top:-20px;"%>
                        <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to session_path(current_user.id), method: :delete do%>
                          <span class="material-icons" style="color:#000;">logout</span>
                        <%end%>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div style="margin-top:100px;">
  <div class="container d-flex justify-content-center">
      <div class="col-10">
          <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body d-flex justify-content-start">
                        <ul class="list-unstyled mb-0">
                            <li class="list-inline-item">
                              <%= image_tag("profile-1.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3 story", width:"50px", height:"auto", style:"") %> <br>
                              <small>maitregimofficel</small>
                            </li>
                            <li class="list-inline-item">
                              <%= image_tag("profile-2.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3 story", width:"50px", height:"auto", style:"") %> <br>
                              <small>christ-brown92</small>
                            </li>
                        </ul>
                    </div>
                </div>

                  <p class="mt-4 mb-3" style="color:#0000ee; text-align:center;">My favorites</p>
                <!--  -->
                <% @favorites.each do |post| %>
                  <div class="card gedf-card mb-5 mt-5">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                           <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                  <%if post.post.image.url%>
                                    <%= image_tag post.post.user.image.url, class: "rounded-circle", width: "45px"%>
                                  <% end %>
                                </div>
                                <div class="ml-2">
                                    <div class="h7 text-muted">
                                      <%= post.user.pseudo + " a publié" %>
                                    </div>
                                </div>
                            </div>
                            <div>
                              <div class="dropdown">
                                  <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      <i class="fa fa-ellipsis-h"></i>
                                  </button>
                                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                      <div class="h6 dropdown-header">Configuration</div>
                                      <% unless post.user_id == current_user.id %>
                                        <% if @favorite.present? %>
                                        <%= link_to 'Supprimer le favori', favorite_path(post_id: @post.id), method: :delete, class:"dropdown-item"%>
                                        <% else %>
                                          <%= link_to 'Ajouter au favoris',
                                          favorites_path(post_id: @post.id), method: :post, class:"dropdown-item"%>
                                        <% end %>
                                      <% end %>
                                    <%= link_to 'Back', posts_path, class:"dropdown-item" %>
                                  </div>
                              </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>

                        <div class="mb-3">
                          <img src="<%= post.post.image.url %>" class="img-fluid" alt="">
                        </div>
                        <p class="card-text">
                          <%= post.post.content %>
                        </p>

                        <div class="pr-3 pb-2">
                          <strong class="d-block">365.354 likes</strong>
                          <strong class="d-block">samkolder</strong>
                          <p class="d-block mb-1">Lil drone shot I got a while back but never posted.</p>
                          <span class="text-muted">View all 2,247 comments</span>

                          <div>
                              <div>
                                <strong class="d-block">a.7.m3ff</strong>
                                <span>❤️💓💓💓💓💓</span>
                              </div>
                              <div>
                                <strong class="d-block">adri_rez77</strong>
                                <span>Hi</span>
                              </div>
                          </div>

                          <small class="text-muted"><%= post.created_at %></small>
                        </div>
                    </div>
                  <div class="card-footer">
                      <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                      <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                      <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                  </div>
              </div>
             <% end %>
            </div>
            <div class="col-md-4">
              <div class="d-flex flex-row align-items-center">
                  <%= image_tag current_user.image.url, :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3", width:"50px", height:"auto"%>
                  <div class="profile-info ml-3">
                      <span class="profile-infousername">
                        <%=current_user.pseudo%>
                      </span>
                  </div>
              </div>

              <div class="mt-4">
                  <div class="d-flex flex-row justify-content-between">
                      <small class="text-muted font-weight-normal">Suggestions For You</small>
                      <small><a href="#" style="text-decoration:none;">See All</a></small>
                  </div>
                  <div>
                      <div class="d-flex flex-row justify-content-between align-items-center mt-3 mb-3">
                          <div class="d-flex flex-row align-items-center">
                              <%= image_tag("profile-3.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3 story", width:"50px", height:"auto", style:"") %>
                              <strong class="ml-3 sugest-username">instagram</strong>
                          </div>
                        <button class="btn btn-primary p-1">Follow</button>
                      </div>
                      <div class="d-flex flex-row justify-content-between align-items-center mt-3 mb-3">
                          <div class="d-flex flex-row align-items-center">
                              <%= image_tag("profile-2.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3", width:"50px", height:"auto", style:"") %>
                              <strong class="ml-3 sugest-username">comics</strong>
                          </div>
                          <button class="btn btn-primary p-1">Follow</button>
                      </div>
                      <div class="d-flex flex-row justify-content-between align-items-center mt-3 mb-3">
                          <div class="d-flex flex-row align-items-center">
                              <%= image_tag("profile-5.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3", width:"50px", height:"auto", style:"") %>
                              <strong class="ml-3 sugest-username">thecw</strong>
                          </div>
                          <button class="btn btn-primary p-1">Follow</button>
                      </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/posts/show.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossorigin="anonymous">

<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
     rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<%= stylesheet_link_tag 'posts', media: 'all', 'data-turbolinks-track': 'reload' %>

<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color:#fff;">
    <div class="container justify-content-center layout">
        <div class="d-flex flex-row justify-content-between align-items-center col-10">
            <a class="navbar-brand" href="#">
                <%= image_tag("ig-logo.png", :alt => "logo") %>
            </a>
            <div class="form-data">
                <form class="" action="#">
                  <input type="text" name="" value="" placeholder="search">
                </form>
            </div>
            <div class="d-flex flex-row">
                <ul class="list-inline m-0">
                    <li class="list-inline-item">
                      <%= link_to posts_path do %>
                        <span class="material-icons" style="color:#000;">home</span>
                      <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to favorites_path do %>
                          <span class="material-icons" style="color:#000;">favorite</span>
                        <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to new_post_path do %>
                          <span class="material-icons" style="color:#000;">add_circle</span>
                        <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to user_path(current_user.id) do%>
                          <%= image_tag current_user.image.url, class:"img-fluid rounded-circle", width:"25px", height:"auto", style:"margin-top:-20px;"%>
                        <% end %>
                    </li>
                    <li class="list-inline-item ml-2">
                        <%= link_to session_path(current_user.id), method: :delete do%>
                          <span class="material-icons" style="color:#000;">logout</span>
                        <%end%>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div style="margin-top:100px;">
  <div class="container d-flex justify-content-center">
      <div class="col-10">
          <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body d-flex justify-content-start">
                        <ul class="list-unstyled mb-0">
                            <li class="list-inline-item">
                              <%= image_tag("profile-1.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3 story", width:"50px", height:"auto", style:"") %> <br>
                              <small>maitregimofficel</small>
                            </li>
                            <li class="list-inline-item">
                              <%= image_tag("profile-2.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3 story", width:"50px", height:"auto", style:"") %> <br>
                              <small>christ-brown92</small>
                            </li>
                        </ul>
                    </div>
                </div>

                  <p class="mt-4 mb-3" style="color:#0000ee;">Post Details</p>
                <!--  -->
                <div class="card gedf-card mb-5 mt-5">
                  <div class="card-header">
                      <div class="d-flex justify-content-between align-items-center">
                         <div class="d-flex justify-content-between align-items-center">
                              <div class="mr-2">
                                <%if @post.user.image.url%>
                                  <%= image_tag @post.user.image.url, class: "rounded-circle", width: "45px"%>
                                <% end %>
                              </div>
                              <div class="ml-2">
                                  <div class="h7 text-muted">
                                    <%= @post.user.pseudo + " a publié" %>
                                  </div>
                              </div>
                          </div>
                          <div>
                            <div class="dropdown">
                                <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-ellipsis-h"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                    <div class="h6 dropdown-header">Configuration</div>
                                    <%if @post.user==current_user %>
                                      <%= link_to 'Edit', edit_post_path(@post), class: "dropdown-item" %>
                                    <% end %>
                                    <% unless @post.user_id == current_user.id %>
                                      <% if @favorite.present? %>
                                      <%= link_to 'Supprimer le favori', favorite_path(post_id: @post.id), method: :delete, class:"dropdown-item"%>
                                      <% else %>
                                        <%= link_to 'Ajouter au favoris',
                                        favorites_path(post_id: @post.id), method: :post, class:"dropdown-item"%>
                                      <% end %>
                                    <% end %>
                                  <%= link_to 'Back', posts_path, class:"dropdown-item" %>
                                </div>
                            </div>
                          </div>
                      </div>
                  </div>
                  <div class="card-body">
                      <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>

                      <div class="mb-3">
                        <img src="<%= @post.image.url %>" class="img-fluid" alt="">
                      </div>
                      <p class="card-text">
                        <%= @post.content %>
                      </p>

                      <div class="pr-3 pb-2">
                        <strong class="d-block">365.354 likes</strong>
                        <strong class="d-block">samkolder</strong>
                        <p class="d-block mb-1">Lil drone shot I got a while back but never posted.</p>
                        <span class="text-muted">View all 2,247 comments</span>

                        <div>
                            <div>
                              <strong class="d-block">a.7.m3ff</strong>
                              <span>❤️💓💓💓💓💓</span>
                            </div>
                            <div>
                              <strong class="d-block">adri_rez77</strong>
                              <span>Hi</span>
                            </div>
                        </div>

                        <small class="text-muted"><%= @post.created_at %></small>
                      </div>
                  </div>
                  <div class="card-footer">
                      <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                      <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                      <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                  </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="d-flex flex-row align-items-center">
                  <%= image_tag current_user.image.url, :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3", width:"50px", height:"auto"%>
                  <div class="profile-info ml-3">
                      <span class="profile-infousername">
                        <%=current_user.pseudo%>
                      </span>
                  </div>
              </div>

              <div class="mt-4">
                  <div class="d-flex flex-row justify-content-between">
                      <small class="text-muted font-weight-normal">Suggestions For You</small>
                      <small><a href="#" style="text-decoration:none;">See All</a></small>
                  </div>
                  <div>
                      <div class="d-flex flex-row justify-content-between align-items-center mt-3 mb-3">
                          <div class="d-flex flex-row align-items-center">
                              <%= image_tag("profile-3.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3 story", width:"50px", height:"auto", style:"") %>
                              <strong class="ml-3 sugest-username">instagram</strong>
                          </div>
                        <button class="btn btn-primary p-1">Follow</button>
                      </div>
                      <div class="d-flex flex-row justify-content-between align-items-center mt-3 mb-3">
                          <div class="d-flex flex-row align-items-center">
                              <%= image_tag("profile-2.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3", width:"50px", height:"auto", style:"") %>
                              <strong class="ml-3 sugest-username">comics</strong>
                          </div>
                          <button class="btn btn-primary p-1">Follow</button>
                      </div>
                      <div class="d-flex flex-row justify-content-between align-items-center mt-3 mb-3">
                          <div class="d-flex flex-row align-items-center">
                              <%= image_tag("profile-5.jpg", :alt => "logo", class:"img-fluid rounded-circle mb-2 ml-3", width:"50px", height:"auto", style:"") %>
                              <strong class="ml-3 sugest-username">thecw</strong>
                          </div>
                          <button class="btn btn-primary p-1">Follow</button>
                      </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>

<div id="wrapper">
  <div class="container">
    <div class="form-data">
      <%= form_with(model: @user, local:true) do |form| %>

        <div class="logo">
          <%= image_tag("logo.png", :alt => "logo") %>
        </div>

        <p style=";font-size:15px;margin-bottom:10px;">Sign up to see photos and videos <br> from your friends</p>

        <a class="facebook-login" href="#">
          <i class="fab fa-facebook-square"></i> Update your profil
        </a>

        <span class="has-separator">O</span>

        <%=form.text_field :pseudo, placeholder:"Pseudo", style: "margin-bottom:10px;"%>

        <%=form.email_field :email, placeholder:"Enter Email", style: "margin-bottom:10px;"%>

        <%=form.password_field :password, placeholder:"password", style: "margin-bottom:10px;"%>

        <%= form.password_field :password_confirmation, placeholder:"Password confirm", style: "margin-bottom:10px;"%>

        <%= form.file_field :image%>

        <%= form.hidden_field :image_cache %>

        <%=form.submit "Update", disable_with: 'Submiting...', class:"form-btn"%>

      <% end %>

      <div class="sign-up">
        Don't want to edit? <%= link_to 'Back', user_path %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>